apiVersion: zarantonello.dev/v1
kind: DnsRecord
metadata:
  name: example-com
  namespace: your-namespace
spec:
  data:
    - A:
        addresses:
          - 192.0.2.1
    - AAAA:
        addresses:
          - 2001:db8::1
  fqdn: example.com
