concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci-rust:latest@sha256:82a34e915a51298e89b5ee43aae6535e86bb06e19b4f6e6e7838b380cfe02670
    name: Check with formatters
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ secrets.SEMANTIC_RELEASE_TOKEN }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Run formatter
        run: cargo fmt --check

name: check-formatter.yaml

"on":
  pull_request:
    branches:
      - main
