concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check:
    container:
      image: git.zarantonello.dev/infra/ci-rust:v1.2.0@sha256:58fbc899f02d3514a7607200abaf2a006f2a92147a5e6e1a0daeef88091cef5a
      volumes:
        - forgejo-runner-cache-cargo-registry:/usr/local/cargo/registry
        - forgejo-runner-cache-projects-kube-dns-rs-target:/target
    env:
      CARGO_TARGET_DIR: /target
    name: Checks
    runs-on: srv-home
    steps:
      - name: Clone the repository
        run: |
          git clone --filter=blob:none --no-checkout https://${{ forge.token }}@git.zarantonello.dev/${{ forge.repository }} ${{ forge.workspace }};
          git checkout --quiet ${{ forge.sha }};
      - name: Run linter
        run: cargo clippy
      - name: Run types and syntax check
        run: cargo check

name: check.yaml

"on":
  pull_request:
    branches:
      - main
