jobs:
  respond:
    container:
      image: git.zarantonello.dev/infra/ci-rust:v1.2.7@sha256:08b32511b6683c06812314b2ad4921e3756b3bc37a5c28d6ec437dde72eff431
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
        - forgejo-runner-cache-cargo-registry:/usr/local/cargo/registry
        - forgejo-runner-cache-projects-kube-dns-rs:/target
    name: LLM Bot response generation
    runs-on: srv-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p ~/.pi/agent/

          cat << 'EOF' > ~/.pi/agent/auth.json
          ${{ secrets.PI_AUTH_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/models.json
          ${{ vars.PI_MODELS_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/settings.json
          ${{ vars.PI_SETTINGS_JSON }}
          EOF
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@3ccbb3078616a890a174d4587498fabd2a101f7a # v1.11.11
        with:
          auth-token: ${{ secrets.CI_BOT_TOKEN }}
          auth-username: ci-bot
          git-author: CI [bot]
          git-email: ci-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
