jobs:
  respond:
    container:
      image: git.zarantonello.dev/infra/ci-rust:v1.2.0@sha256:58fbc899f02d3514a7607200abaf2a006f2a92147a5e6e1a0daeef88091cef5a
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
        - forgejo-runner-cache-cargo-registry:/usr/local/cargo/registry
        - forgejo-runner-cache-projects-kube-dns-rs:/target
    name: LLM Bot response generation
    runs-on: srv-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p ~/.pi/agent/

          cat << 'EOF' > ~/.pi/agent/auth.json
          ${{ secrets.PI_AUTH_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/models.json
          ${{ vars.PI_MODELS_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/settings.json
          ${{ vars.PI_SETTINGS_JSON }}
          EOF
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@d06b79127bb5924d2ca542f3c4a39418985b0edf # v1.9.12
        with:
          auth-token: ${{ secrets.CI_BOT_TOKEN }}
          auth-username: ci-bot
          git-author: CI [bot]
          git-email: ci-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
