jobs:
  respond:
    container:
      image: git.zarantonello.dev/infra/ci-rust:v1.2.1@sha256:5e5a80a9f111855679206795e50c385b918dcabe92e1ecac35cde5fbfa61f9ca
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
        - forgejo-runner-cache-cargo-registry:/usr/local/cargo/registry
        - forgejo-runner-cache-projects-kube-dns-rs:/target
    name: LLM Bot response generation
    runs-on: srv-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p ~/.pi/agent/

          cat << 'EOF' > ~/.pi/agent/auth.json
          ${{ secrets.PI_AUTH_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/models.json
          ${{ vars.PI_MODELS_JSON }}
          EOF

          cat << 'EOF' > ~/.pi/agent/settings.json
          ${{ vars.PI_SETTINGS_JSON }}
          EOF
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@fcf3d1aac43c73d72c4c9b318427f59bf38ee668 # v1.9.13
        with:
          auth-token: ${{ secrets.CI_BOT_TOKEN }}
          auth-username: ci-bot
          git-author: CI [bot]
          git-email: ci-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
