services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/infra/ci-rust:latest@sha256:82a34e915a51298e89b5ee43aae6535e86bb06e19b4f6e6e7838b380cfe02670
    ports:
      - 1053:1053/tcp
      - 1053:1053/udp
    volumes:
      - ..:/workspace:z,cached
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /workspace

volumes:
  cargo-cache: {}
