services:
  workspace:
    entrypoint: sleep infinity
    image: git.zarantonello.dev/infra/ci-rust:v1.2.0@sha256:58fbc899f02d3514a7607200abaf2a006f2a92147a5e6e1a0daeef88091cef5a
    ports:
      - 1053:1053/tcp
      - 1053:1053/udp
    volumes:
      - ..:/workspace:z,cached
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /workspace

volumes:
  cargo-cache: {}
